language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
#for now running no tests
script: notests
  #- pytest $TEST_SUITE # or py.test for Python versions 3.5 and below